image: "python:3.13.11"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip install uv
  - export UV_LINK_MODE=copy
  - uv venv
  - source .venv/bin/activate
  - uv sync
  - mkdir -p static/all_image

stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  script:
    - pre-commit install
    - make lint

pytest:
  stage: Test
  script:
    - make test
