services:
  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  pytex:
    build:
      context: .
      dockerfile: Dockerfile
    image: pytex:local
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    volumes:
      - /tmp:/tmp
    depends_on:
      - redis

volumes:
  redis_data:
